-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 13:25:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WildCircusDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WildCircusDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WildCircusDB` DEFAULT CHARACTER SET utf8 ;
USE `WildCircusDB` ;

-- -----------------------------------------------------
-- Table `WildCircusDB`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WildCircusDB`.`admin` (
  `idadmin` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WildCircusDB`.`acts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WildCircusDB`.`acts` (
  `idacts` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`idacts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WildCircusDB`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WildCircusDB`.`ticket` (
  `idcategory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `price` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WildCircusDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WildCircusDB`.`user` (
  `iduser` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `ticket_idcategory` INT NOT NULL,
  PRIMARY KEY (`iduser`, `ticket_idcategory`),
  INDEX `fk_user_ticket_idx` (`ticket_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_user_ticket`
    FOREIGN KEY (`ticket_idcategory`)
    REFERENCES `WildCircusDB`.`ticket` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WildCircusDB`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WildCircusDB`.`message` (
  `idmessage` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `content` MEDIUMTEXT NULL,
  PRIMARY KEY (`idmessage`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
